### ISSUE TITLE
punctuation affecting url generation

### ISSUE THREAD

**Issue by MartinPons** [JosiahParry/genius#25]
Hi

I just found your package. Thanks for the work you've putted in it. I'm use to work with tidyverse in R so it's great for me. I think I've might found an issue though

I was downloading the discography of the band Savatage, but two albums were missing

"Streets: a Rock opera", "Dead Winter Dead

This is the error returned when I query for the first of these two albums

```
genius_album(artist = "Savatage", album = "Streets: A Rock Opera")

Error in mutate_impl(.data, dots) : 
  Evaluation error: '"So after pouring out his heart to God and getting no answers, at least nothing verbal. DT headed back downtown. Excuse me, excuse me, are you done with that cigarette? I'll take that. God bless you. Thank you, thank you. Ah. Camel no filter, my favorite. I love it. Where was I? Where was I? Oh yeah, oh yeah, so DT headed back downtown to the Bowery where he bumped into this old friend of mine. A real moaning old cager. Who told him:"Get out of this town. Pack your things. Start over somewhere else. Cause New York City, it don't mean nothing."' does not exist in current working directory
```

 then my current directory

If this helps, I suspect that it has to do with these albums having narrated parts. The text in the error above is the narrated part for the song "New York City don't mean Nothing", before the actual song, which appeared in an album reedition years after its original release. It turns out that Genius has an url for the narration, 

https://genius.com/Savatage-narration-to-new-york-city-dont-mean-nothing-lyrics

And here it is the url with the lyrics for the actual song

https://genius.com/Savatage-new-york-city-dont-mean-nothing-lyrics

"Dead Winter Dead" also has narrated parts, the error I've returned  here is

```
genius_album(artist = "Savatage", album = "Dead Winter Dead")

Error in mutate_impl(.data, dots) : 
  Evaluation error: 'Instrumental' does not exist in current working directory

```
and my current directory.

I hope this helps

Thanks again for the work

**Comment by JosiahParry** [comment]
The problem is that you’re using the function for whole albums for songs.
Use genius_lyrics() instead.

**Comment by JosiahParry** [comment]
Oh, interesting. This has to do with the way you wrote the song title. The apostrophe threw it off. So if you remove that, it will work. This is a problem I should address.

------

`prep_info()` creates a space for an apostrophe rather than a removes it. `gen_song_url()` creates the url `"https://genius.com/savatage-new-york-city-don-t-mean-nothing-lyrics"`. There should be no dash between n and t.

**Comment by MartinPons** [comment]
Ok. I see. Great :)

Thanks again

**Comment by JosiahParry** [comment]
Hey! This has been fixed :)
