### ISSUE TITLE
Correct URL fails to get album's lyrics

### ISSUE THREAD

**Issue by GiankDiluvi** [JosiahParry/genius#26]
Hi Josiah,

I have been using your package for the last couple of months and it's been pretty useful; thanks! 

However, I am having some trouble with retrieving a certain album's lyrics: Paul Simon's Graceland. When I run `genius::genius_album("Paul Simon", "Graceland")` I get the following error:

> Error in mutate_impl(.data, dots) : 
  Evaluation error: Not Found (HTTP 404)..

I know this error has to do with the URL generated by GeniusR not matching the actual one on Genius, and for the most part it's related to special characters or how Genius manages some specific URLs. It's not the first time I encounter it but usually it's solved just by looking at the URL in Genius and modifying the album/artist info in R accordingly.

However, it seems to me that the URL generated by GeniusR is correct. If I run `genius::gen_album_url("Paul Simon", "Graceland")` I get the URL [https://genius.com/albums/Paul-Simon/Graceland](https://genius.com/albums/Paul-Simon/Graceland), which is correct and does take you to the right Genius page. Moreover, there are no special characters or anything of the sort; it's a pretty simple album title and artist name too.

Lastly, I had already retrieved this particular album's lyrics a couple of months ago, so if this is a bug, it's a new one.

Given that GeniusR does generate the correct URL, I don't know if the problem lies with the package, Genius.com, or even my computer. Can you reproduce this error? BTW, I just updated the 
`genius` package, have the latest version of R installed (3.5.2), and am running everything on a 64-bit Windows 10 computer, if it helps. Also, this issue only seems to happen with this particular album. I am currently getting data for other ones and I have encountered no errors so far.

Thank you.

**Comment by JosiahParry** [comment]
The error has been spotted. Track 15 says `(Missing Lyrics)` next to it. 

So if you run `genius_tracklist("Paul Simon", "Graceland")` it gives you all of the listed tracks and their urls. What is interesting is that `genius` finds a url for the track `You Can Call Me Al (demo version)`  but when I inspect the page I don't see it. 

This is a very weird behaviour.

**Comment by GiankDiluvi** [comment]
Thank you for your quick answer.

I'm pretty sure the issue is that lyrics for `You Can Call Me Al (demo version)`, the 15th track of the album, are missing in Genius.com. Indeed, I manually retrieved lyrics for all other songs of the album with no problem. It seems that `genius` finds URLs for songs even if their lyrics are missing, and so fails when trying to retrieve them.

The good news is that this is somewhat solvable by verifying if a certain album's lyrics are missing, in which case it is easy to obtain the rest of the lyrics using `genius_tracklist` and filtering out the unwanted song. Not as neat but it works.

Anyway, thank you, Josiah.

**Comment by JosiahParry** [comment]
Hey, @GiankDiluvi! I know it's super late, but I want you to know that this has been fixed in a commit (https://github.com/JosiahParry/genius/commit/df6fa9c9697eea15516690b501fa671879038cf9)

**Comment by GiankDiluvi** [comment]
Thank you for the update, Josiah!
