### ISSUE TITLE
genius_album returning empty data frame when only some lyrics in album exist

### ISSUE THREAD

**Issue by tsoukinator** [JosiahParry/genius#34]
Hello there Josiah,

Many thanks for this API wrapper - I have been using it extensively for some lyric sentiment analysis.

I've noticed some artists won't download lyrics of, even if provided the correct album name.
This particular instance, may be caused as some songs in this album do not have lyrics. 
I'm guessing some smart error handling is causing the code to stop entirely upon hitting a song with no lyrics, rather than skipping to the next track.

To provide an example, this query will fail:
genius::possible_album(artist = "Daryl Braithwaite", album="Edge", info="all")

Although, this query, for a song from the same album, succeeds:
genius::possible_lyrics(artist = "Daryl Braithwaite",song="As The Days Go By",info="all")

For reference, here is the source artefact:
https://genius.com/albums/Daryl-braithwaite/Edge

**Comment by JosiahParry** [comment]
Hi @tsoukinator! Thank's for the issue.

I wasn't able to replicate. Can you run `packageVersion("genius")`? If it is not 2.2.0 I would recommend updating. 

``` r
# test albums
edge <- genius::genius_album(artist = "Daryl Braithwaite", album = "Edge", info = "all")

edge_p <- genius::possible_album(artist = "Daryl Braithwaite", album = "Edge", info = "all")

# test lyrics
days <- genius::genius_lyrics(artist = "Daryl Braithwaite",song="As The Days Go By",info="all")

days_p <- genius::possible_lyrics(artist = "Daryl Braithwaite",song="As The Days Go By",info="all")

# all work
```

<sup>Created on 2019-07-29 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by tsoukinator** [comment]
Wow, I'm truly living in the past!
> packageVersion("genius")
[1] ‘0.0.1.0’

> packageVersion("genius")
[1] ‘2.2.0’

Issue was solved as well! Looks like a like has changed since I first started using your package.

Thanks for the super quick reply, I'll keep in touch with you in the future if I find anything else which could be improved.

**Comment by JosiahParry** [comment]
That's great to hear! I'd love to learn more about how you're using genius. Feel free to message me on [twitter](https://twitter.com/JosiahParry) or via [email](mailto:josiah.parry@gmail.com).

Perhaps [this draft writeup](https://github.com/JosiahParry/genre-classification/tree/master/write-up) may be of use to you. This shows how I've been going about getting data from spotifyr along with genius.
