### ISSUE TITLE
Differences of album/artist names between Spotify and Genius

### ISSUE THREAD

**Issue by tsoukinator** [JosiahParry/genius#35]
Hello again Josiah,

Would be keen to know what you think about this one.

I've been using data from Spotify (artists/albums/song names) and obtaining data via the spotifyr "get_artist_features" call. I'm then using this data to provide me with artist/album/song names, which I then feed to your "possible_albums"call.

I've run into a few issues with differences between naming conventions for both spotify/genius.
e.g. Artist: "**The** Smashing Pumpkins" vs "Smashing Pumpkins", 
e.g. Album: "Years **and** Years" vs "Years **&** Years". _(<- this one is just an example)_

Upon observing issues such as these, I've begun trying to code my way around them, and produce a loop statement to say "If nothing is returned, try another variation of the same name".

I don't see this as an issue of the genius package itself, as I understand it really is a data problem. If you had scope to look into solving this, I'd be very excited. Meanwhile, I'm happy to keep you up to date with my progress on trying to solve this from my end.

**Comment by tsoukinator** [comment]
Looking even into the Smashing Pumpkins example I provided, it appears both Spotify and Genius are now aligned on this artist name. Will have to speak up when I notice another discrepancy.

In saying so, it might be better looking for the long term solution, and me filling out one of these forms to help Spotify with their own data quality:
https://support.spotify.com/us/contact-spotify-support/#_=_

**Comment by JosiahParry** [comment]
Hm. Frankly, I think a lot of this could be solved by the `prep_info()` function within genius. It just requires identifying and recording each idiosyncrasy. For the most part the relationship between the two naming conventions are mostly right. With my newer package [`bbcharts`](https://github.com/JosiahParry/bbcharts), I am becoming even more aware of the inconsistencies. 

If you're willing to take a stab at it, I'd love to see what you come up with. And fwiw, Genius includes the `The` `https://genius.com/The-smashing-pumpkins-1979-lyrics`
