### ISSUE TITLE
add_genius() gives warning about cols being required

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [JosiahParry/genius#37]
Running the example code from the README for getting lyrics for multiple albums at once 

```r
artist_albums <- tribble(
     ~artist, ~album,
     "J. Cole", "KOD",
     "Sampha", "Process"
)

artist_albums %>%
     add_genius(artist, album)
```

works but gives the following warning

```r
Warning message:
`cols` is now required.
Please use `cols = c(lyrics)` 
```

I think it has to do with recent changes in tidyr and the following line

https://github.com/JosiahParry/genius/blob/f7d7d5e8c7f976918daa226fc53b3731fb80cfc1/R/add_genius.R#L53

**Comment by JosiahParry** [comment]
🙄 I had a feeling this day would come. Thank you for letting me know! I’ll
try and push a patch up to GH tomorrow.

**Comment by JosiahParry** [comment]
Fixed in https://github.com/JosiahParry/genius/pull/38.

Please let me know if for any reason this doesn't help :)
