### ISSUE TITLE
genius_album(..., info = "all") and (..., info = "title") produces an error

### ISSUE THREAD

**Issue by chris-billingham** [JosiahParry/genius#39]
Hi there,

Seems that two colums of `track_title` are coming through when you select either of these two options:
``` r
genius::genius_album(artist = "radiohead", album = "ok computer", 
    info = "all")
#> Error: Column name `track_title` must not be duplicated.
#> Use .name_repair to specify repair.
```

<sup>Created on 2019-12-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

``` r
genius::genius_album(artist = "radiohead", album = "ok computer", 
    info = "title")
#> Error: Column name `track_title` must not be duplicated.
#> Use .name_repair to specify repair.
```

<sup>Created on 2019-12-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I've got a fix though so I'll raise a PR in on this shortly whilst also changing the default arg for genius_album.

**Comment by chris-billingham** [comment]
Hmmm, my fix doesn't seem to do what I meant it to do. Leave it with me.

**Comment by JosiahParry** [comment]
Hi Chris! Thank you for pointing this out. If you're up to making the PR, I'd thoroughly appreciate that! 

With this, though, changing the default arg of `genius_album()` may break or alter the way that `add_genius()` works. This could be by passed by adding an `...` arg to `add_genius()` and passing that into the internal `map2()` calls or adding the arg `info = "simple"` to the map2 call.

**Comment by chris-billingham** [comment]
Hi Josiah,

Personally I've turned against making all the default for this, partly due to my implementation of the fix and amendment. I'll leave it as simple and be explicit in the docs on what setting `info = "all"` actually does.

**Comment by chris-billingham** [comment]
I have fixed this
