### ISSUE TITLE
CRAN availability

### ISSUE THREAD

**Issue by Nicolas-Gallo** [JosiahParry/genius#48]
It seems that the package was removed from the CRAN repository.
Do you plan on making it available again?

**Comment by JosiahParry** [comment]
Well that's news to me. I wasn't informed. I'll have to figure out what is up there.

**Comment by Nicolas-Gallo** [comment]
Alright, thank you for your work.

**Comment by JosiahParry** [comment]
Also, congrats on the first issue!!

**Comment by Nicolas-Gallo** [comment]
Oh I see.
I'm actually using it for my master thesis so that's why I was kinda reactive.
Anyway, I already did most of what I wanted to do with it, it was really useful!

**Comment by JosiahParry** [comment]
Just because it’s not on CRAN doesn’t mean you can’t use it! You can
install it (if somehow it’s heen uninstalled) with
`remotes::install_github(“Josiahparry/genius”)`.

**Comment by Nicolas-Gallo** [comment]
Oh right, I definetely should have thought about it.
Thank you.
