### ISSUE TITLE
trouble installing package

### ISSUE THREAD

**Issue by milicajevremovic** [JosiahParry/genius#53]
Hi @JosiahParry, I have problem with installing genius package in RStudio. Starting from this: devtools::install_github('charlie86/genius')
Any clues what is going on?

**Comment by JosiahParry** [comment]
Yup! The package is mine not charlies! 

`remotes::install_github("Josiahparry/genius")`

**Comment by milicajevremovic** [comment]
Yes, I made a little writing mistake! I tried **remotes::install_github("Josiahparry/genius")** and ended up with this: 

> Enter one or more numbers separated by spaces, or an empty line to cancel
> 1: 3
> Installing 1 packages: digest
> Installing package into ‘C:/Users/Milica/Documents/R/win-library/3.5’
> (as ‘lib’ is unspecified)
> trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/digest_0.6.25.zip'
> Content type 'application/zip' length 248623 bytes (242 KB)
> downloaded 242 KB
> 
> package ‘digest’ successfully unpacked and MD5 sums checked
> Error: (converted from warning) cannot remove prior installation of package ‘digest’`

**Comment by JosiahParry** [comment]
Hey! So your issue is with the package digest. Can you install that package on it's own? And does the CRAN installation work for you?

Can you try `install.packages("genius")`? There is no difference between the development version and the released version right now.

**Comment by milicajevremovic** [comment]
Yeah! It works now! Thank you again @JosiahParry 👍
