### ISSUE TITLE
Lyrics aren't being pulled

### ISSUE THREAD

**Issue by malihanda** [JosiahParry/genius#58]
Was trying to use the examples [here](https://cran.r-project.org/web/packages/genius/vignettes/genius_basics.html) to pull lyrics for an album, but and they aren't working. For example, when I do `DNA <- genius_lyrics(artist = "Kendrick Lamar", song = "DNA.")` then I get:

```
Error: 'NA' does not exist in current working directory ('C:/Users/handa/Documents/').
In addition: Warning messages:
1: In if (grepl("\n", file)) { :
  the condition has length > 1 and only the first element will be used
2: In if (grepl("\n", path)) return(path) :
  the condition has length > 1 and only the first element will be used
3: In if (is_url(path)) { :
  the condition has length > 1 and only the first element will be used
4: In if (file.exists(path)) return(normalizePath(path, "/", mustWork = FALSE)) :
  the condition has length > 1 and only the first element will be used
5: In if (!is_absolute_path(path)) paste0(" in current working directory ('",  :
  the condition has length > 1 and only the first element will be used
```

I tried with a few other songs / artists and am getting similar results. I also tried running a script I had from last year (which worked perfectly fine back then.) I have made no changes to it, but now I'm getting similar errors.

If I do `df = genius_album(artist = "Taylor Swift", album = "evermore")` then this doesn't pull the lyrics. 

First I get warnings:
```
Warning messages:
1: In if (grepl("\n", file)) { ... :
  the condition has length > 1 and only the first element will be used
2: In if (grepl("\n", path)) return(path) :
  the condition has length > 1 and only the first element will be used
3: In if (is_url(path)) { ... :
  the condition has length > 1 and only the first element will be used
4: In if (file.exists(path)) return(normalizePath(path, "/",  ... :
  the condition has length > 1 and only the first element will be used
5: In if (!is_absolute_path(path)) paste0(" in current working directory ('",  ... :
  the condition has length > 1 and only the first element will be used
6: In if (grepl("\n", file)) { ... :
  the condition has length > 1 and only the first element will be used
7: In if (grepl("\n", path)) return(path) :
  the condition has length > 1 and only the first element will be used
8: In if (is_url(path)) { ... :
  the condition has length > 1 and only the first element will be used
9: In if (file.exists(path)) return(normalizePath(path, "/",  ... :
  the condition has length > 1 and only the first element will be used
# many more
```

And then the data frame doesn't have any lyrics in it:

```
   track_title                     track_n
   <chr>                             <int>
 1 ​willow                                1
 2 ​champagne problems                    2
 3 ​gold rush                             3
 4 ​'tis the damn season                  4
 5 ​tolerate it                           5
 6 ​no body, no crime (Ft. HAIM)          6
 7 ​happiness                             7
 8 ​dorothea                              8
 9 ​coney island (Ft. The National)       9
10 ​ivy                                  10
11 ​cowboy like me                       11
12 ​l​ong story short                     12
13 ​marjorie                             13
14 ​closure                              14
15 ​evermore (Ft. Bon Iver)              15
```

Not sure if this is a versioning issue on my end? Or did something about Genius change? Or did the package functions get updated so that now you request lyrics in a different way?

**Comment by JosiahParry** [comment]
Hey! I just pushed changes to the package yesterday to address this issue. Can you please try the development version from github? I'm working through the CRAN release currently.

**Comment by running-machin** [comment]
> Hey! I just pushed changes to the package yesterday to address this issue. Can you please try the development version from github? I'm working through the CRAN release currently.

how to install the development package?

**Comment by JosiahParry** [comment]
@running-machin  You can run `remotes::install_github("josiahparry/genius")`.

**Comment by malihanda** [comment]
Any ideas when the CRAN release will be updated? The dev version isn't working for me. (I can't install it, I keep getting errors that I'm missing other packages.)

```
ERROR: dependencies 'rvest', 'tidytext' are not available for package 'genius'
* removing 'C:/Users/handa/Documents/R/win-library/3.5/genius'
In R CMD INSTALL
Warning messages:
1: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying [filepath]curl.dll to [filepath]curl.dll: Permission denied
2: In i.p(...) :
  installation of package ‘lifecycle’ had non-zero exit status
3: In i.p(...) : installation of package ‘pillar’ had non-zero exit status
4: In i.p(...) :
  installation of package ‘tidytext’ had non-zero exit status
5: In i.p(...) : installation of package ‘rvest’ had non-zero exit status
6: In i.p(...) :
  installation of package ‘[filepath]genius_2.2.3.tar.gz’ had non-zero exit status
```

**Comment by JosiahParry** [comment]
@malihanda I am working on this. I'm trying to address CRAN check notes.

This message you provided indicates that your machine is preventing you from installing it due to permissions. The development version installs fine in an empty package environment.

**Comment by JosiahParry** [comment]
Submitted to CRAN. The fix is pending their approval.

**Comment by durkeepk** [comment]
I'm using the dev version and I might have a similar issue, where lyrics do not seem to be retrieved. I was able to successfully use your package to get a few thousand lyrics a couple weeks ago, but now everything just returns NA. Any ideas about what might be wrong?

`remotes::install_github("josiahparry/genius")
library(genius)

emotions_math <- genius_album(artist = "Margaret Glaspy", album = "Emotions and Math")`

<img width="421" alt="Screen Shot 2021-06-02 at 10 40 35 AM" src="https://user-images.githubusercontent.com/44843328/120510367-f8179700-c38e-11eb-8c5b-ab5a711707e2.png">

**Comment by JosiahParry** [comment]
@durkeepk 
The code still works here for the development version (sorry for the delayed release, having trouble with CRAN). 

If you're planning on doing _a lot_ of lyric fetching I'd recommend building in some random `Sys.sleep()` calls so that your IP doesn't get blocked by Genius. I support I could build in an option to add random sleep noise to the calls. 


![image](https://user-images.githubusercontent.com/13534508/120517736-c4dd0400-c39e-11eb-9745-00a402714f63.png)

**Comment by redapemusic35** [comment]
> @durkeepk
> The code still works here for the development version (sorry for the delayed release, having trouble with CRAN).
> 
> If you're planning on doing _a lot_ of lyric fetching I'd recommend building in some random `Sys.sleep()` calls so that your IP doesn't get blocked by Genius. I support I could build in an option to add random sleep noise to the calls.
> 
> ![image](https://user-images.githubusercontent.com/13534508/120517736-c4dd0400-c39e-11eb-9745-00a402714f63.png)

Hi Josiah, your dev fix worked for me. However, I was wondering if you could elaborate a bit more on Sys.sleep functions? I am pretty bad at this.

**Comment by redapemusic35** [comment]
So I think that this issue (https://github.com/JosiahParry/genius/issues/60) is the same as the one here. However, though I installed the dev version, I am still getting the same results.

**Comment by durkeepk** [comment]
Yeah it was working again for a while after this issue was closed, but now it is not with the dev version or the CRAN version as far as I can tell.

**Comment by JosiahParry** [comment]
I'll submit to CRAN this weekend and confirm the bug you've reported.

However, my guess is that you're making too many calls to genius too quickly and they're blocking you.

**Comment by JosiahParry** [comment]
The issue is that genius is changing the element classes which are used for identifying the lyrics. Pushing changes to the repo then submitting to cran shortly.
