### ISSUE TITLE
genius_tracklist error

### ISSUE THREAD

**Issue by LukasLoTo** [JosiahParry/genius#64]
Hello,
Just used both `genius_tracklist` and `genius_album` for some code:
`soda1 = genius_album(artist = "Soda Stereo", album = "Cancion animal")`
`ca1 = genius_tracklist(artist = "Soda Stereo", album = "Cancion animal") %>% 
  filter(track_title == "(En) El Séptimo Día")`
And it worked fine. However, when doing the same thing for another album, only `genius_album` works. When using `genius_tracklist` i get:
```
Error in read_html.response(x$response, ..., base_url = x$url) : 
  Not Found (HTTP 404).
Además: Warning message:
In session_set_response(x, resp) : Not Found (HTTP 404).
```
I double checked the spelling and tried re-running the code. 
``` r
soda2 = genius_album(artist = "Soda Stereo", album = "Soda Stereo")
ss1 = genius_tracklist(artist = "Soda Stero", album = "Soda Stereo")
```

**Comment by LukasLoTo** [comment]
Also, conflicts seem to be more prone to happen with spanish songs. Is there any reason for this?

**Comment by JosiahParry** [comment]
You're getting a 404 error. This likely means that you're sending far too
many request far too frequently and are getting blocked by genius.
